package cmd

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var genTypesOut string

var genTypesCmd = &cobra.Command{
	Use:   "types",
	Short: "Generate TypeScript types from your database schema",
	Long:  `Fetches table metadata from the OmniBase API and writes TypeScript definitions. Requires OMNIBASE_ANON_KEY or --key (service role for full schema).`,
	RunE:  runGenTypes,
}

func init() {
	genCmd := &cobra.Command{Use: "gen", Short: "Generate code or config"}
	genCmd.AddCommand(genTypesCmd)
	rootCmd.AddCommand(genCmd)
	genTypesCmd.Flags().StringVarP(&genTypesOut, "out", "o", "omnibase-types.ts", "Output file path")
}

func runGenTypes(cmd *cobra.Command, args []string) error {
	if apiKey == "" {
		return fmt.Errorf("API key required: set OMNIBASE_ANON_KEY or use --key")
	}
	req, err := http.NewRequest("GET", url+"/pg/tables?schema=public", nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("API returned %d: %s", resp.StatusCode, string(body))
	}

	var tables []struct {
		Name   string `json:"name"`
		Schema string `json:"schema"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&tables); err != nil {
		return fmt.Errorf("decode response: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Generated by omnibase gen types. Do not edit by hand.\n\n")
	buf.WriteString("export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]\n\n")
	buf.WriteString("export interface Database {\n  public: {\n    Tables: {\n")

	for _, t := range tables {
		buf.WriteString(fmt.Sprintf("      %s: { Row: Record<string, Json>; Insert: Record<string, Json>; Update: Partial<Record<string, Json>> }\n", t.Name))
	}

	buf.WriteString("    }\n  }\n}\n\n")
	buf.WriteString("export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']\n")

	outPath := genTypesOut
	if !filepath.IsAbs(outPath) && outPath != "-" {
		outPath = filepath.Join(".", outPath)
	}
	if outPath == "-" {
		_, _ = os.Stdout.Write(buf.Bytes())
		return nil
	}
	return os.WriteFile(outPath, buf.Bytes(), 0o644)
}
